# Generated by Django 5.1.7 on 2025-04-03 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birth', '0002_alter_birthcertificateapplication_status_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
